# Generated by Django 4.2.28 on 2026-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='real_height_m',
            field=models.FloatField(default=100.0, help_text='Real-world height of the market in metres. Used to calibrate route distances.'),
        ),
        migrations.AddField(
            model_name='market',
            name='real_width_m',
            field=models.FloatField(default=100.0, help_text='Real-world width of the market in metres. Used to calibrate route distances.'),
        ),
        migrations.AlterField(
            model_name='market',
            name='map_height',
            field=models.PositiveIntegerField(default=1000, help_text='Logical height of the map coordinate space.'),
        ),
        migrations.AlterField(
            model_name='market',
            name='map_width',
            field=models.PositiveIntegerField(default=1000, help_text='Logical width of the map coordinate space (e.g. pixels or metres).'),
        ),
        migrations.AlterField(
            model_name='node',
            name='label',
            field=models.CharField(help_text="Human-readable label, e.g. 'Stall 24', 'Entrance A', 'Junction B3'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='x',
            field=models.FloatField(default=0.0, help_text='Horizontal position on the map.'),
        ),
        migrations.AlterField(
            model_name='node',
            name='y',
            field=models.FloatField(default=0.0, help_text='Vertical position on the map.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, help_text="Short code used in direction instructions, e.g. 'ZA', 'FOOD'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='color_hex',
            field=models.CharField(default='#AED6F1', help_text='Hex colour for rendering this zone on the SVG map overlay.', max_length=7),
        ),
    ]
