# Generated by Django 4.2.28 on 2026-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_map_height_alter_market_map_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='map_image',
            field=models.FileField(blank=True, help_text='Upload an SVG or image of the market floor plan.', null=True, upload_to='maps/'),
        ),
    ]
