# Generated by Django 4.2.28 on 2026-05-07 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_real_height_m_market_real_width_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='map_image',
            field=models.FileField(blank=True, help_text='Upload an SVG or image of the market floor plan.', null=True, upload_to='maps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
