# Generated by Django 4.2.28 on 2026-05-06 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_real_height_m_market_real_width_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Nigerian Naira (NGN). Optional for MVP.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Optional emoji or icon class for UI display, e.g. '🍅' or 'fa-apple-alt'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='What product categories this vendor sells.', related_name='vendors', to='vendors.productcategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of what this vendor sells.'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='node',
            field=models.OneToOneField(blank=True, help_text='The stall/node this vendor occupies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='markets.node'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional: link to a Django user account for vendor login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (include country code, e.g. +234...)', max_length=20),
        ),
    ]
